export const relationshipOptions = [
  "Partner",
  "Wife",
  "Husband",
  "Mother",
  "Father",
  "Daughter",
  "Son",
  "Sister",
  "Brother",
  "Grandmother",
  "Grandfather",
  "Aunt",
  "Uncle",
  "Cousin",
  "Niece",
  "Nephew",
  "Girlfriend",
  "Boyfriend",
  "Friend",
  "Colleague",
  "Boss",
  "Family Member",
];

export const genderOptions = ["Unspecified Gender", "Male", "Female", "Other"];
